package xml_vectors;

public class SpitXml {

	public static void main(String[] args) {
		@SuppressWarnings("unused")
		final String xml = "<piv:customDefinition xmlns:piv=\"http://api.nedstat.com/qda/pivottable/1.0\" xmlns:filter=\"http://api.nedstat.com/qda/filter/1.0\">"
				+ "<piv:rowGroupingItems>"
				+ "<piv:group>"
				+ "<piv:item>"
				+ "<piv:className>custom.microsoft_analytics.TextLabel</piv:className>"
				+ "<piv:itemType>string</piv:itemType>"
				+ "<piv:userTitle>"
				+ "<piv:translation>"
				+ "<piv:lcid>3090</piv:lcid>"
				+ "<piv:text>Site</piv:text>"
				+ "</piv:translation>"
				+ "</piv:userTitle>"
				+ "<piv:argumentValues>"
				+ "<piv:argumentValue>x_site</piv:argumentValue>"
				+ "</piv:argumentValues>"
				+ "<piv:propagationScope>EVENT</piv:propagationScope>"
				+ "<piv:propagationRule>CURRENT</piv:propagationRule>"
				+ "</piv:item>"
				+ "<piv:range xsi:nil=\"true\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"/>"
				+ "</piv:group>"
				+ "</piv:rowGroupingItems>"
				+ "<piv:columnGroupingItems>"
				+ "<piv:group>"
				+ "<piv:item>"
				+ "<piv:className>custom.microsoft_analytics.TextLabel</piv:className>"
				+ "<piv:itemType>string</piv:itemType>"
				+ "<piv:userTitle>"
				+ "<piv:translation>"
				+ "<piv:lcid>3090</piv:lcid>"
				+ "<piv:text>Site</piv:text>"
				+ "</piv:translation>"
				+ "</piv:userTitle>"
				+ "<piv:argumentValues>"
				+ "<piv:argumentValue>x_site</piv:argumentValue>"
				+ "</piv:argumentValues>"
				+ "<piv:propagationScope>EVENT</piv:propagationScope>"
				+ "<piv:propagationRule>CURRENT</piv:propagationRule>"
				+ "</piv:item>"
				+ "<piv:range xsi:nil=\"true\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"/>"
				+ "</piv:group>"
				+ "</piv:columnGroupingItems>"
				+ "<piv:parameterItems/>"
				+ "<piv:dataItems>"
				+ "<piv:column>"
				+ "<piv:item>"
				+ "<piv:className>custom.microsoft_analytics.Visitors</piv:className>"
				+ "<piv:itemType>integer</piv:itemType>"
				+ "<piv:userTitle>"
				+ "<piv:translation>"
				+ "<piv:lcid>3090</piv:lcid>"
				+ "<piv:text>Visitors</piv:text>"
				+ "</piv:translation>"
				+ "</piv:userTitle>"
				+ "<piv:argumentValues/>"
				+ "<piv:propagationScope>VISITOR</piv:propagationScope>"
				+ "<piv:propagationRule>FIRST_VALUE_TO_ALL</piv:propagationRule>"
				+ "</piv:item>"
				+ "<piv:aggregator>"
				+ "<piv:className>Sum</piv:className>"
				+ "</piv:aggregator>"
				+ "<piv:visitorFilter xsi:nil=\"true\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"/>"
				+ "<piv:visitFilter xsi:nil=\"true\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"/>"
				+ "<piv:eventFilter xsi:nil=\"true\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"/>"
				+ "<piv:formatPattern></piv:formatPattern>"
				+ "<piv:isHidden>false</piv:isHidden>"
				+ "</piv:column>"
				+ "</piv:dataItems>"
				+ "<piv:displayMode>hierarchical</piv:displayMode>"
				+ "<piv:dftRowViewMode>collapsed</piv:dftRowViewMode>"
				+ "<piv:dftColumnViewMode>expanded</piv:dftColumnViewMode>"
				+ "<piv:chartItems/>"
				+ "</piv:customDefinition>";

		String xml2 = "<ns3:customDefinition>"
				+ "<ns4:rowGroupingItems>"
				+ "<ns4:group>"
				+ "<ns4:item>"
				+ "<ns4:className>standard.PageUrl</ns4:className>"
				+ "<ns4:itemType>string</ns4:itemType>"
				+ "<ns4:userTitle>"
				+ "<ns4:translation>"
				+ "<ns4:lcid>3090</ns4:lcid>"
				+ "<ns4:text>Page URL</ns4:text>"
				+ "</ns4:translation>"
				+ "</ns4:userTitle>"
				+ "<ns4:argumentValues/>"
				+ "<ns4:propagationScope>EVEN</ns4:propagationScope>"
				+ "<ns4:propagationRule>CURRENT</ns4:propagationRule>"
				+ "</ns4:item>"
				+ "<ns4:range xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:nil=\"true\"/>"
				+ "</ns4:group>"
				+ "<ns4:group>"
				+ "<ns4:item>"
				+ "<ns4:className>standard.Label</ns4:className>"
				+ "<ns4:itemType>string</ns4:itemType>"
				+ "<ns4:userTitle>"
				+ "<ns4:translation>"
				+ "<ns4:lcid>3090</ns4:lcid>"
				+ "<ns4:text>Labels</ns4:text>"
				+ "</ns4:translation>"
				+ "</ns4:userTitle>"
				+ "<ns4:argumentValues>"
				+ "<ns4:argumentValue>name</ns4:argumentValue>"
				+ "</ns4:argumentValues>"
				+ "<ns4:propagationScope>EVENT</ns4:propagationScope>"
				+ "<ns4:propagationRule>CURRENT</ns4:propagationRule>"
				+ "</ns4:item>"
				+ "<ns4:range xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:nil=\"true\"/>"
				+ "</ns4:group>"
				+ "<ns4:group>"
				+ "<ns4:item>"
				+ "<ns4:className>standard.Label</ns4:className>"
				+ "<ns4:itemType>string</ns4:itemType>"
				+ "<ns4:userTitle>"
				+ "<ns4:translation>"
				+ "<ns4:lcid>3090</ns4:lcid>"
				+ "<ns4:text>Valeurs</ns4:text>"
				+ "</ns4:translation>"
				+ "</ns4:userTitle>"
				+ "<ns4:argumentValues>"
				+ "<ns4:argumentValue>name</ns4:argumentValue>"
				+ "</ns4:argumentValues>"
				+ "<ns4:propagationScope>EVENT</ns4:propagationScope>"
				+ "<ns4:propagationRule>CURRENT</ns4:propagationRule>"
				+ "</ns4:item>"
				+ "<ns4:range xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:nil=\"true\"/>"
				+ "</ns4:group>"
				+ "<ns4:group>"
				+ "<ns4:item>"
				+ "<ns4:className>standard.Event</ns4:className>"
				+ "<ns4:itemType>string</ns4:itemType>"
				+ "<ns4:userTitle>"
				+ "<ns4:translation>"
				+ "<ns4:lcid>3090</ns4:lcid>"
				+ "<ns4:text>Standard events</ns4:text>"
				+ "</ns4:translation>"
				+ "</ns4:userTitle>"
				+ "<ns4:argumentValues/>"
				+ "<ns4:propagationScope>EVENT</ns4:propagationScope>"
				+ "<ns4:propagationRule>CURRENT</ns4:propagationRule>"
				+ "</ns4:item>"
				+ "<ns4:range xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:nil=\"true\"/>"
				+ "</ns4:group>"
				+ "</ns4:rowGroupingItems>"
				+ "<ns4:columnGroupingItems/>"
				+ "<ns4:parameterItems/>"
				+ "<ns4:dataItems/>"
				+ "<ns4:displayMode>hierarchical</ns4:displayMode>"
				+ "<ns4:dftRowViewMode>collapsed</ns4:dftRowViewMode>"
				+ "<ns4:dftColumnViewMode>collapsed</ns4:dftColumnViewMode>"
				+ "<ns4:chartItems/>"
				+ "</ns3:customDefinition>";
		System.out.println(xml2);
	}
}
